### ISSUE TITLE
TVODefaultAudioDevice doesn't appear to be seen as a subclass of TVOAudioDevice

### ISSUE THREAD

**Issue by RobTF** [dkornev/TwilioVoiceXamarinIOS#1]
From the Twilio Quickstart it looks as though the TVODefaultAudioDevice class should be assignable to TwilioVoice.AudioDevice, but it isn't as it is not a subclass of TVOAudioDevice.

Looking at the bindings it seems this was the intention but doesn't seem to be the case.

**Comment by RobTF** [comment]
I've left a pull request which appears to fix this, I've tried it locally and I can make an outgoing call using CallKit so it looks good from what I can see.

**Comment by dkornev** [comment]
I looked briefly at your PR and it looks good to me. I need to check a few scenarios but I don't think anything will break so expect to merge it soon. Thanks a lot for your contribution!
WIll publish new NuGet package tood

**Comment by dkornev** [comment]
I'll keep it opened as a reminder to publish a new version of NuGet package

**Comment by dkornev** [comment]
3.1.0.1 package updated
