### ISSUE TITLE
How to use this project

### ISSUE THREAD

**Issue by NVentimiglia** [dkornev/TwilioVoiceXamarinIOS#11]
I am continuing to have issues with the nuget package and I am wondering if including the library is a better path. When I download the project I am missing the libTwilioVoice.so file. I ran the pod install, and ran the xcode project it generated, but now what ?

I also do not understand the sh bootstrap.sh you have in the readme. I dont even see this file in the project.

**Comment by Ulrizza** [comment]
It may be a little late for you, but I found this blog post with explanations and a sample of this project in use. I found it extremely useful :-)
https://medium.com/@san.thanki/callkit-pushkit-twilio-with-xamarin-83553f93be86

**Comment by dkornev** [comment]
@Ulrizza Thank you very much. I appreciate your help and I hope it will help others with the binding.
