### ISSUE TITLE
Linker error

### ISSUE THREAD

**Issue by softsan** [dkornev/TwilioVoiceXamarinIOS#12]
Hi,

I forked your repo and tried to add latest twilio ios sdk (5.4.1) but when i try to integrate in my iOS project, i'm getting bunch of errors (it works in debug build, but in release mode it failed on iOS project) already have this in iOS project -> mtouch argument `--registrar:static -cxx -gcc_flags -dead_strip` :
```
Native linking failed, undefined Objective-C class: TVOStatsReport. The symbol '_OBJC_CLASS_$_TVOStatsReport' could not be found in any of the libraries or frameworks linked with your application.
MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: TVORemoteTrackStats. The symbol '_OBJC_CLASS_$_TVORemoteTrackStats' could not be found in any of the libraries or frameworks linked with your application.
MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: TVOOpusCodec. The symbol '_OBJC_CLASS_$_TVOOpusCodec' could not be found in any of the libraries or frameworks linked with your application.
MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: TVOLocalTrackStats. The symbol '_OBJC_CLASS_$_TVOLocalTrackStats' could not be found in any of the libraries or frameworks linked with your application.
```

i changed twilio sdk download link in cartfile.resolved and Cartfile 
binary "https://raw.githubusercontent.com/twilio/twilio-voice-ios/Releases/twilio-voice-ios.json" "5.4.1"

i see some redline error in apidefinition.cs file

<img width="1358" alt="Screenshot 2020-06-30 at 12 02 54 AM" src="https://user-images.githubusercontent.com/7391319/86042658-1c734100-ba65-11ea-8ea2-df1f52ee6d1f.png">

**Comment by softsan** [comment]
Hi 

I see you updated nuget for iOS 5.4.1
but it also gives me linker error.

```
Native linking failed, undefined Objective-C class: TVOStatsReport. The symbol '_OBJC_CLASS_$_TVOStatsReport' could not be found in any of the libraries or frameworks linked with your application.
MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: TVORemoteTrackStats. The symbol '_OBJC_CLASS_$_TVORemoteTrackStats' could not be found in any of the libraries or frameworks linked with your application.
MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: TVOOpusCodec. The symbol '_OBJC_CLASS_$_TVOOpusCodec' could not be found in any of the libraries or frameworks linked with your application.
MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: TVOLocalTrackStats. The symbol '_OBJC_CLASS_$_TVOLocalTrackStats' could not be found in any of the libraries or frameworks linked with your application.

```

**Comment by softsan** [comment]
@dkornev Hi any updates on this? thanks.

**Comment by dkornev** [comment]
@softsan Hi.
I personally don't have this issue. I'll take a look at this one when I have time

**Comment by dkornev** [comment]
Did you try to add --registrar:static -cxx -gcc_flags -dead_strip flags?

**Comment by softsan** [comment]
@dkornev  yes it is already there. 
--registrar:static -cxx -gcc_flags -dead_strip 
It works fine in debug mode but failed release mode.

**Comment by puneetk207** [comment]
@softsan please put --registrar:static -cxx -gcc_flags -dead_strip for release mode also.

**Comment by softsan** [comment]
Its working with latest nuget package.

**Comment by dkornev** [comment]
@softsan Thank you

**Comment by softsan** [comment]
@dkornev no worries! I’ve also created an end to end sample  https://github.com/softsan/callkitsample  for Twilio in case you want to mention in your repo.  It uses CallKit as well and can be use without it.
