### ISSUE TITLE
MTOUCH: Error MT5210: Native linking failed, undefined symbol: std::__1::

### ISSUE THREAD

**Issue by sylendra7** [dkornev/TwilioVoiceXamarinIOS#5]
Hi getting build error ,

/clang: Error: linker command failed with exit code 1 (use -v to see invocation)

MTOUCH: Error MT5210: Native linking failed, undefined symbol: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::replace(unsigned long, unsigned long, char const*, unsigned long). Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. (MT5210)

**Comment by dkornev** [comment]
Hi.
What version of the SDK are you using?

**Comment by sylendra7** [comment]
Hi 

=== Visual Studio Community 2019 for Mac ===
Version 8.2.6 (build 73)
=== Xamarin.iOS ===

Version: 13.0.0.19 (Visual Studio Community)
Hash: b02da292
Branch: xcode11
Build date: 2019-09-12 14:26:59-0400

**Comment by dkornev** [comment]
Are you using the latest binding version too?

**Comment by sylendra7** [comment]
@dkornev  Yes , using the latest

**Comment by dkornev** [comment]
I'll take a look at these later next week. Sorry, don't have any time right now. But I'm also using the latest version of the binding and don't have any issues.

**Comment by sylendra7** [comment]
@dkornev  thanks for your commitment . I will wait for the fix

**Comment by sylendra7** [comment]
@dkornev ,below is the complete build errors(103) i'm getting . May be it will help a bit 

MTOUCH: Error MT5210: Native linking failed, undefined symbol: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::assign(char const*, unsigned long). Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. (MT5210) (KBB.iOS)
MTOUCH: Error MT5210: Native linking failed, undefined symbol: std::__1::chrono::steady_clock::now(). Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. (MT5210) (KBB.iOS)
MTOUCH: Error MT5210: Native linking failed, undefined symbol: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__grow_by(unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long). Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. (MT5210) (KBB.iOS)
MTOUCH: Error MT5210: Native linking failed, undefined symbol: std::nothrow. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. (MT5210) (KBB.iOS)
MTOUCH: Error MT5210: Native linking failed, undefined symbol: std::__1::basic_istream<char, std::__1::char_traits<char> >::operator>>(unsigned short&). Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. (MT5210) (KBB.iOS)
MTOUCH: Error MT5210: Native linking failed, undefined symbol: std::__1::basic_istream<char, std::__1::char_traits<char> >::operator>>(unsigned int&). Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. (MT5210) (KBB.iOS)
/MTOUCH: Error MT5210: Native linking failed, undefined symbol: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::at(unsigned long) const. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. (MT5210) (KBB.iOS)
/MTOUCH: Error MT5210: Native linking failed, undefined symbol: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::compare(char const*) const. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. (MT5210) (KBB.iOS)
/MTOUCH: Error MT5210: Native linking failed, undefined symbol: ___cxa_call_unexpected. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. (MT5210) (KBB.iOS)
/MTOUCH: Error MT5210: Native linking failed, undefined symbol: std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<<(unsigned short). Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. (MT5210) (KBB.iOS)
//MTOUCH: Error MT5210: Native linking failed, undefined symbol: void std::__1::__sort<std::__1::__less<int, int>&, int*>(int*, int*, std::__1::__less<int, int>&). Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. (MT5210) (KBB.iOS)
/MTOUCH: Error MT5210: Native linking failed, undefined symbol: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::replace(unsigned long, unsigned long, char const*, unsigned long). Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. (MT5210) (KBB.iOS)
MTOUCH: Error MT5210: Native linking failed, undefined symbol: std::__1::regex_error::regex_error(std::__1::regex_constants::error_type). Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. (MT5210) (KBB.iOS)
MTOUCH: Error MT5210: Native linking failed, undefined symbol: typeinfo for std::__1::regex_error. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. (MT5210) (KBB.iOS)
/MTOUCH: Error MT5210: Native linking failed, undefined symbol: std::__1::regex_error::~regex_error(). Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. (MT5210) (KBB.iOS)
/MTOUCH: Error MT5210: Native linking failed, undefined symbol: std::__1::stol(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long*, int). Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. (MT5210) (KBB.iOS)
//MTOUCH: Error MT5210: Native linking failed, undefined symbol: std::__1::basic_istream<char, std::__1::char_traits<char> >::operator>>(double&). Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. (MT5210) (KBB.iOS)
/Users/sylujyothi/Projects/KBB/KBB.iOS/MTOUCH: Error MT5210: Native linking failed, undefined symbol: std::__1::locale::locale(std::__1::locale const&). Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. (MT5210) (KBB.iOS)
/Users/sylujyothi/Projects/KBB/KBB.iOS/MTOUCH: Error MT5210: Native linking failed, undefined symbol: typeinfo for std::bad_cast. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. (MT5210) (KBB.iOS)
/Users/sylujyothi/Projects/KBB/KBB.iOS/MTOUCH: Error MT5210: Native linking failed, undefined symbol: std::__1::basic_istream<char, std::__1::char_traits<char> >::tellg(). Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. (MT5210) (KBB.iOS)
/Users/sylujyothi/Projects/KBB/KBB.iOS/MTOUCH: Error MT5210: Native linking failed, undefined symbol: std::__1::basic_istream<char, std::__1::char_traits<char> >::~basic_istream(). Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. (MT5210) (KBB.iOS)
/Users/sylujyothi/Projects/KBB/KBB.iOS/MTOUCH: Error MT5210: Native linking failed, undefined symbol: operator new(unsigned long, std::nothrow_t const&). Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. (MT5210) (KBB.iOS)
/Users/sylujyothi/Projects/KBB/KBB.iOS/MTOUCH: Error MT5210: Native linking failed, undefined symbol: std::runtime_error::runtime_error(char const*). Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. (MT5210) (KBB.iOS)
/Users/sylujyothi/Projects/KBB/KBB.iOS/MTOUCH: Error MT5210: Native linking failed, undefined symbol: vtable for std::range_error. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. (MT5210) (KBB.iOS)
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: "std::logic_error::logic_error(char const*)", referenced from: (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: twilio::synchronize(rtc::Thread&) in libTwilioVoice.a(timer.cpp.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: "typeinfo for std::range_error", referenced from: (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: resip::Data::resize(unsigned int, bool) in libTwilioVoice.a(Data.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: "typeinfo for std::bad_alloc", referenced from: (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: resip::Data::Data(char const*, unsigned int) in libTwilioVoice.a(Data.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: resip::Data::Data(unsigned char const*, unsigned int) in libTwilioVoice.a(Data.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: resip::Data::Data(char const*) in libTwilioVoice.a(Data.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: resip::Data::Data(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libTwilioVoice.a(Data.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: resip::Data::Data(resip::Data const&) in libTwilioVoice.a(Data.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: resip::Data::substr(unsigned int, unsigned int) const in libTwilioVoice.a(Data.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: GCC_except_table10 in libTwilioVoice.a(ConnectionBase.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: ... (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: "std::__1::__vector_base_common<true>::__throw_out_of_range() const", referenced from: (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: std::__1::vector<rtc::InterfaceAddress, std::__1::allocator<rtc::InterfaceAddress> >::at(unsigned long) const in libTwilioVoice.a(network.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: twilio::stats::get(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >, std::__1::function<twilio::media::StatsReport (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<webrtc::StatsReport const*, std::__1::allocator<webrtc::StatsReport const*> > const&)> const&, std::__1::function<void (std::__1::vector<twilio::media::StatsReport, std::__1::allocator<twilio::media::StatsReport> >)> const&, std::__1::function<void (webrtc::StatsObserver*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)> const&) in libTwilioVoice.a(stats_collector.cpp.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: std::__1::vector<rtc::scoped_refptr<webrtc::MediaStreamInterface>, std::__1::allocator<rtc::scoped_refptr<webrtc::MediaStreamInterface> > >::at(unsigned long) in libTwilioVoice.a(peerconnection.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: std::__1::vector<cricket::ContentInfo, std::__1::allocator<cricket::ContentInfo> >::at(unsigned long) in libTwilioVoice.a(jsepsessiondescription.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: std::__1::vector<cricket::CryptoParams, std::__1::allocator<cricket::CryptoParams> >::at(unsigned long) in libTwilioVoice.a(mediasession.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: "std::__1::basic_istream<char, std::__1::char_traits<char> >::operator>>(unsigned long&)", referenced from: (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: webrtc::ParseContent(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, cricket::MediaType, int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<int, std::__1::allocator<int> > const&, unsigned long*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, bool*, int*, cricket::MediaContentDescription*, cricket::TransportDescription*, std::__1::vector<webrtc::JsepIceCandidate*, std::__1::allocator<webrtc::JsepIceCandidate*> >*, webrtc::SdpParseError*) in libTwilioVoice.a(webrtcsdp.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::at(unsigned long)", referenced from: (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: rtc::CreateRandomData(unsigned long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) in libTwilioVoice.a(helpers.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: "std::__1::__get_classname(char const*, bool)", referenced from: (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: unsigned int std::__1::regex_traits<char>::__lookup_classname<std::__1::__wrap_iter<char const*> >(std::__1::__wrap_iter<char const*>, std::__1::__wrap_iter<char const*>, bool, char) const in libTwilioVoice.a(voice_sdp_utils.cpp.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: "std::__1::basic_istream<char, std::__1::char_traits<char> >::operator>>(int&)", referenced from: (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: bool (anonymous namespace)::FindConstraint<int>(webrtc::MediaConstraintsInterface const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int*, unsigned long*) in libTwilioVoice.a(mediaconstraintsinterface.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: webrtc::(anonymous namespace)::GetSctpPort(cricket::SessionDescription const*) in libTwilioVoice.a(peerconnection.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: int rtc::FromString<int>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libTwilioVoice.a(videocapturertracksource.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: cricket::Codec::GetParam(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int*) const in libTwilioVoice.a(codec.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: bool rtc::FromString<int>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int*) in libTwilioVoice.a(webrtcsdp.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: webrtc::ParsePort(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int*) in libTwilioVoice.a(iceserverparsing.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: bool rtc::FromString<int>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int*) in libTwilioVoice.a(mediasession.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: ... (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: "std::__1::basic_istream<char, std::__1::char_traits<char> >::seekg(long long, std::__1::ios_base::seekdir)", referenced from: (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: resip::Data::fromFile(resip::Data const&) in libTwilioVoice.a(Data.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: "std::__1::basic_ostream<char, std::__1::char_traits<char> >::sentry::sentry(std::__1::basic_ostream<char, std::__1::char_traits<char> >&)", referenced from: (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libTwilioVoice.a(call_impl.cpp.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: "std::__1::basic_ostream<char, std::__1::char_traits<char> >::sentry::~sentry()", referenced from: (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libTwilioVoice.a(call_impl.cpp.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: "std::__1::to_string(unsigned int)", referenced from: (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: twilio::voice::CallImpl::OnIceCandidate(webrtc::IceCandidateInterface const*) in libTwilioVoice.a(call_impl.cpp.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: "std::__1::to_string(long long)", referenced from: (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: twilio::voice::processReportAndPostEvent(twilio::media::StatsReport const&, twilio::media::StatsReport const&, twilio::voice::EventObserver&) in libTwilioVoice.a(call_impl.cpp.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: "std::__1::to_string(double)", referenced from: (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: twilio::voice::processReportAndPostEvent(twilio::media::StatsReport const&, twilio::media::StatsReport const&, twilio::voice::EventObserver&) in libTwilioVoice.a(call_impl.cpp.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: "std::__1::basic_istream<char, std::__1::char_traits<char> >::~basic_istream()", referenced from: (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: construction vtable for std::__1::basic_istream<char, std::__1::char_traits<char> >-in-std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libTwilioVoice.a(header_helper.cpp.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: construction vtable for std::__1::basic_istream<char, std::__1::char_traits<char> >-in-std::__1::basic_istringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libTwilioVoice.a(mediaconstraintsinterface.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: construction vtable for std::__1::basic_istream<char, std::__1::char_traits<char> >-in-std::__1::basic_ifstream<char, std::__1::char_traits<char> > in libTwilioVoice.a(Data.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: construction vtable for std::__1::basic_istream<char, resip::DataStream::char_traits<char> >-in-resip::DataStream in libTwilioVoice.a(DataStream.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: "vtable for std::__1::basic_ios<char, std::__1::char_traits<char> >", referenced from: (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: resip::oDataStream::oDataStream(resip::Data&) in libTwilioVoice.a(DataStream.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: resip::DataStream::DataStream(resip::Data&) in libTwilioVoice.a(DataStream.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: resip::SHA1Stream::SHA1Stream() in libTwilioVoice.a(SHA1Stream.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: resip::MD5Stream::MD5Stream() in libTwilioVoice.a(MD5Stream.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: NOTE: a missing vtable usually means the first non-inline virtual member function has no definition. (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: "std::__1::__next_prime(unsigned long)", referenced from: (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: std::__1::__hash_table<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::__unordered_map_hasher<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, std::__1::__unordered_map_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, std::__1::allocator<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >::rehash(unsigned long) in libTwilioVoice.a(peerconnection.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: std::__1::__hash_table<std::__1::__hash_value_type<resip::DialogSetId, resip::DialogSet*>, std::__1::__unordered_map_hasher<resip::DialogSetId, std::__1::__hash_value_type<resip::DialogSetId, resip::DialogSet*>, std::__1::hash<resip::DialogSetId>, true>, std::__1::__unordered_map_equal<resip::DialogSetId, std::__1::__hash_value_type<resip::DialogSetId, resip::DialogSet*>, std::__1::equal_to<resip::DialogSetId>, true>, std::__1::allocator<std::__1::__hash_value_type<resip::DialogSetId, resip::DialogSet*> > >::rehash(unsigned long) in libTwilioVoice.a(DialogUsageManager.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: std::__1::__hash_table<webrtc::AudioReceiveStream*, std::__1::hash<webrtc::AudioReceiveStream*>, std::__1::equal_to<webrtc::AudioReceiveStream*>, std::__1::allocator<webrtc::AudioReceiveStream*> >::rehash(unsigned long) in libTwilioVoice.a(audio_state.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: std::__1::__hash_table<unsigned short, std::__1::hash<unsigned short>, std::__1::equal_to<unsigned short>, std::__1::allocator<unsigned short> >::rehash(unsigned long) in libTwilioVoice.a(video_send_stream.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: std::__1::__hash_table<std::__1::__hash_value_type<int, int>, std::__1::__unordered_map_hasher<int, std::__1::__hash_value_type<int, int>, std::__1::hash<int>, true>, std::__1::__unordered_map_equal<int, std::__1::__hash_value_type<int, int>, std::__1::equal_to<int>, true>, std::__1::allocator<std::__1::__hash_value_type<int, int> > >::rehash(unsigned long) in libTwilioVoice.a(mediasession.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: std::__1::__hash_table<std::__1::__hash_value_type<unsigned long, resip::Handled*>, std::__1::__unordered_map_hasher<unsigned long, std::__1::__hash_value_type<unsigned long, resip::Handled*>, std::__1::hash<unsigned long>, true>, std::__1::__unordered_map_equal<unsigned long, std::__1::__hash_value_type<unsigned long, resip::Handled*>, std::__1::equal_to<unsigned long>, true>, std::__1::allocator<std::__1::__hash_value_type<unsigned long, resip::Handled*> > >::rehash(unsigned long) in libTwilioVoice.a(HandleManager.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: std::__1::__hash_table<std::__1::__hash_value_type<resip::Mime, resip::ContentsFactoryBase*>, std::__1::__unordered_map_hasher<resip::Mime, std::__1::__hash_value_type<resip::Mime, resip::ContentsFactoryBase*>, std::__1::hash<resip::Mime>, true>, std::__1::__unordered_map_equal<resip::Mime, std::__1::__hash_value_type<resip::Mime, resip::ContentsFactoryBase*>, std::__1::equal_to<resip::Mime>, true>, std::__1::allocator<std::__1::__hash_value_type<resip::Mime, resip::ContentsFactoryBase*> > >::rehash(unsigned long) in libTwilioVoice.a(SipMessage.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: ... (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: "virtual thunk to std::__1::basic_istream<char, std::__1::char_traits<char> >::~basic_istream()", referenced from: (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: construction vtable for std::__1::basic_istream<char, std::__1::char_traits<char> >-in-std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libTwilioVoice.a(header_helper.cpp.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: construction vtable for std::__1::basic_istream<char, std::__1::char_traits<char> >-in-std::__1::basic_istringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libTwilioVoice.a(mediaconstraintsinterface.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: construction vtable for std::__1::basic_istream<char, std::__1::char_traits<char> >-in-std::__1::basic_ifstream<char, std::__1::char_traits<char> > in libTwilioVoice.a(Data.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: construction vtable for std::__1::basic_istream<char, resip::DataStream::char_traits<char> >-in-resip::DataStream in libTwilioVoice.a(DataStream.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::append(unsigned long, char)", referenced from: (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: rtc::HttpParseAttributes(char const*, unsigned long, std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >&) in libTwilioVoice.a(httpcommon.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: "std::__1::basic_iostream<char, std::__1::char_traits<char> >::~basic_iostream()", referenced from: (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: construction vtable for std::__1::basic_iostream<char, std::__1::char_traits<char> >-in-std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libTwilioVoice.a(header_helper.cpp.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: construction vtable for std::__1::basic_iostream<char, resip::DataStream::char_traits<char> >-in-resip::DataStream in libTwilioVoice.a(DataStream.o) (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/error MT5209: Error: "non-virtual thunk to std::__1::basic_iostream<char, std::__1::char_traits<char> >::~basic_iostream()", referenced from: (KBB.iOS) Native linking
/Users/sylujyothi/Projects/KBB/KBB.iOS/MTOUCH: Error MT5202: Native linking failed. Please review the build log. (MT5202) (KBB.iOS)
/Users/sylujyothi/Projects/KBB/KBB.iOS/clang: Error: linker command failed with exit code 1 (use -v to see invocation) (KBB.iOS)

**Comment by sylendra7** [comment]
Hi @dkornev ,

can you provide atleast any temporary solution for this ...?



Regards
Sylendra

**Comment by dkornev** [comment]
Hi @sylendra7 ,
I believe that the temporary solution would be to find a reason for the issue. The same NuGet package works fine for me. I think that it might be something in your settings:

- Change build log verbosity to _Diagnostic_ to see full build logs, it may help
- Be sure that you have _<MtouchExtraArgs>--registrar:static</MtouchExtraArgs>_ in you csproj 
- Check your _MtouchLink_ settings to be sure that you link SDKonly

**Comment by sylendra7** [comment]
Hi @dkornev , 

I attached the logs , Can you please help me with that ...?

[logs.zip](https://github.com/dkornev/TwilioVoiceXamarinIOS/files/3664057/logs.zip)



Regards
Sylendra

**Comment by dkornev** [comment]
Can you create a new Xamarin iOS project from a template, add this NuGet package and try to build it?

Let me know if you have the same issue there

**Comment by sylendra7** [comment]
@dkornev , I will create it , before that I have to tell onething , once I added the nugget and build the solution , it is succeeded .If I add any code related to the twilio voice library I'm getting these build errors . If I commented that twilio code and build the project means again it will succeed .

**Comment by sylendra7** [comment]
@dkornev Created the new Xamarin iOS project and added the  below properties 
   public TVOCallInvite CallInvite { get; private set; }
        public TVOCall Call { get; private set; }

got the build errors ... Same thing happens ...

**Comment by sylendra7** [comment]
Hi @dkornev ,

Did you get a chance to check the logs ...? Can you please help me with this as I didn't seen any suspicious in the build logs ... It will be very helpful if you help me for my project ...


Thanks & Regards
Sylendra

**Comment by dkornev** [comment]
@sylendra7 not yet. Will take a look later this week

**Comment by sylendra7** [comment]
Hi @dkornev ,

Deleting DerivedData folder in the Xcode solved my issue .
"library/Developer/Xcode/DerivedData" ===> this is the path .



Regards
Sylendra

**Comment by dkornev** [comment]
@sylendra7 

Thank you for updating this! I'm glad you have figured that out.
