### ISSUE TITLE
IceServer Setting is not working in iOS

### ISSUE THREAD

**Issue by sauravchaudhary94** [dkornev/TwilioVoiceXamarinIOS#6]
I am trying to add iceServer in My ConnectOptions. But I am getting error. Below is the Code Snippet and Error:
I have just created iceServerList with Server Details and UserCredentials details , working Fine in Android But in iOS I am facing this issue.
 TVOIceOptions iceOptions = TVOIceOptions.OptionsWithBlock((arg0) => { arg0.Servers = iceServers.ToArray();}); 

Error:
Attempting to JIT compile method 'Twilio.Voice.iOS.TVOIceOptionsBuilder:set_Servers (Twilio.Voice.iOS.TVOIceServer[])' while running in aot-only mode.

Can you Please Check It and let me know If you are also facing this issue? I am using version Twilio.Voice.Ios.XamarinBinding( 3.1.0.1 ).

**Comment by dkornev** [comment]
I would recommend you to update the SDK to the latest version (which is currently v5.0.0) and try it there.

Let me know if it helps

**Comment by sauravchaudhary94** [comment]
Updated to latest SDK , still facing the same issue.

**Comment by dkornev** [comment]
@sauravchaudhary94 
Letting you know that I've started investigating it. Have no ideas so far
