### ISSUE TITLE
How do you use this library ? Getting the MT5210 Native Linker Errors

### ISSUE THREAD

**Issue by NVentimiglia** [dkornev/TwilioVoiceXamarinIOS#9]
My experience is identical to this :
https://github.com/dkornev/TwilioVoiceXamarinIOS/issues/5

Here are my steps

-  New Xamarin iOS project
- Add Twilio Voice Nuget Package
- Add the -- registrar:static MTouch flag
- Build and deploy to device (Works!)
- Copy over the sample files into the project
- https://github.com/dkornev/TwilioVoiceXamarinIOS/tree/master/sample
- Build. Fails with 103 errors.
- Is there a step I am missing? Do I need to include the .a file? Do I need to add the linker file ? It seems that something with how we are overriding the extern methods is breaking this.

/TwilioVoice/TwilioHub3.iOS/MTOUCH: Error MT5210: Native linking failed, undefined symbol: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::assign(char const*, unsigned long). Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. (MT5210) (TwilioHub3.iOS)
/TwilioVoice/TwilioHub3.iOS/MTOUCH: Error MT5210: Native linking failed, undefined symbol: std::__1::chrono::steady_clock::now(). Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. (MT5210) (TwilioHub3.iOS)
/TwilioVoice/TwilioHub3.iOS/MTOUCH: Error MT5210: Native linking failed, undefined symbol: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__grow_by(unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long). Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. (MT5210) (TwilioHub3.iOS)
/TwilioVoice/TwilioHub3.iOS/MTOUCH: Error MT5210: Native linking failed, undefined symbol: std::nothrow. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. (MT5210) (TwilioHub3.iOS)
/TwilioVoice/TwilioHub3.iOS/MTOUCH: Error MT5210: Native linking failed, undefined symbol: std::__1::basic_istream<char, std::__1::char_traits<char> >::operator>>(unsigned short&). Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. (MT5210) (TwilioHub3.iOS)
/TwilioVoice/TwilioHub3.iOS/MTOUCH: Error MT5210: Native linking failed, undefined symbol: std::__1::basic_istream<char, std::__1::char_traits<char> >::operator>>(unsigned int&). Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. (MT5210) (TwilioHub3.iOS)
/TwilioVoice/TwilioHub3.iOS/MTOUCH: Error MT5210: Native linking failed, undefined symbol: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::at(unsigned long) const. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. (MT5210) (TwilioHub3.iOS)
/TwilioVoice/TwilioHub3.iOS/MTOUCH: Error MT5210: Native linking failed, undefined symbol: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::compare(char const*) const. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. (MT5210) (TwilioHub3.iOS)
/TwilioVoice/TwilioHub3.iOS/MTOUCH: Error MT5210: Native linking failed, undefined symbol: ___cxa_call_unexpected. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. (MT5210) (TwilioHub3.iOS)
/TwilioVoice/TwilioHub3.iOS/MTOUCH: Error MT5210: Native linking failed, undefined symbol: std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<<(unsigned short). Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. (MT5210) (TwilioHub3.iOS)
/TwilioVoice/TwilioHub3.iOS/MTOUCH: Error MT5210: Native linking failed, undefined symbol: void std::__1::__sort<std::__1::__less<int, int>&, int*>(int*, int*, std::__1::__less<int, int>&). Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. (MT5210) (TwilioHub3.iOS)
/TwilioVoice/TwilioHub3.iOS/MTOUCH: Error MT5210: Native linking failed, undefined symbol: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::replace(unsigned long, unsigned long, char const*, unsigned long). Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. (MT5210) (TwilioHub3.iOS)
/TwilioVoice/TwilioHub3.iOS/MTOUCH: Error MT5210: Native linking failed, undefined symbol: std::__1::regex_error::regex_error(std::__1::regex_constants::error_type). Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. (MT5210) (TwilioHub3.iOS)
/TwilioVoice/TwilioHub3.iOS/MTOUCH: Error MT5210: Native linking failed, undefined symbol: typeinfo for std::__1::regex_error. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. (MT5210) (TwilioHub3.iOS)
/TwilioVoice/TwilioHub3.iOS/MTOUCH: Error MT5210: Native linking failed, undefined symbol: std::__1::regex_error::~regex_error(). Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. (MT5210) (TwilioHub3.iOS)
/TwilioVoice/TwilioHub3.iOS/MTOUCH: Error MT5210: Native linking failed, undefined symbol: std::__1::stol(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long*, int). Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. (MT5210) (TwilioHub3.iOS)
/TwilioVoice/TwilioHub3.iOS/MTOUCH: Error MT5210: Native linking failed, undefined symbol: std::__1::basic_istream<char, std::__1::char_traits<char> >::operator>>(double&). Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. (MT5210) (TwilioHub3.iOS)
/TwilioVoice/TwilioHub3.iOS/MTOUCH: Error MT5210: Native linking failed, undefined symbol: std::__1::locale::locale(std::__1::locale const&). Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. (MT5210) (TwilioHub3.iOS)
/TwilioVoice/TwilioHub3.iOS/MTOUCH: Error MT5210: Native linking failed, undefined symbol: typeinfo for std::bad_cast. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. (MT5210) (TwilioHub3.iOS)
/TwilioVoice/TwilioHub3.iOS/MTOUCH: Error MT5210: Native linking failed, undefined symbol: std::__1::basic_istream<char, std::__1::char_traits<char> >::tellg(). Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. (MT5210) (TwilioHub3.iOS)
/TwilioVoice/TwilioHub3.iOS/MTOUCH: Error MT5210: Native linking failed, undefined symbol: operator new(unsigned long, std::nothrow_t const&). Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. (MT5210) (TwilioHub3.iOS)
/TwilioVoice/TwilioHub3.iOS/MTOUCH: Error MT5210: Native linking failed, undefined symbol: std::runtime_error::runtime_error(char const*). Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. (MT5210) (TwilioHub3.iOS)
/TwilioVoice/TwilioHub3.iOS/MTOUCH: Error MT5210: Native linking failed, undefined symbol: vtable for std::range_error. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. (MT5210) (TwilioHub3.iOS)
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: "std::logic_error::logic_error(char const*)", referenced from: (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: twilio::synchronize(rtc::Thread&) in libTwilioVoice.a(timer.cpp.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: "typeinfo for std::logic_error", referenced from: (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: twilio::synchronize(rtc::Thread&) in libTwilioVoice.a(timer.cpp.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: "typeinfo for std::range_error", referenced from: (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: resip::Data::resize(unsigned int, bool) in libTwilioVoice.a(Data.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: "std::__1::__vector_base_common<true>::__throw_out_of_range() const", referenced from: (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: std::__1::vector<rtc::InterfaceAddress, std::__1::allocator<rtc::InterfaceAddress> >::at(unsigned long) const in libTwilioVoice.a(network.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: twilio::stats::get(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >, std::__1::function<twilio::media::StatsReport (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<webrtc::StatsReport const*, std::__1::allocator<webrtc::StatsReport const*> > const&)> const&, std::__1::function<void (std::__1::vector<twilio::media::StatsReport, std::__1::allocator<twilio::media::StatsReport> >)> const&, std::__1::function<void (webrtc::StatsObserver*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)> const&) in libTwilioVoice.a(stats_collector.cpp.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: std::__1::vector<rtc::scoped_refptr<webrtc::MediaStreamInterface>, std::__1::allocator<rtc::scoped_refptr<webrtc::MediaStreamInterface> > >::at(unsigned long) in libTwilioVoice.a(peerconnection.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: std::__1::vector<cricket::ContentInfo, std::__1::allocator<cricket::ContentInfo> >::at(unsigned long) in libTwilioVoice.a(jsepsessiondescription.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: std::__1::vector<cricket::CryptoParams, std::__1::allocator<cricket::CryptoParams> >::at(unsigned long) in libTwilioVoice.a(mediasession.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: "std::__1::basic_istream<char, std::__1::char_traits<char> >::operator>>(unsigned long&)", referenced from: (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: webrtc::ParseContent(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, cricket::MediaType, int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<int, std::__1::allocator<int> > const&, unsigned long*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, bool*, int*, cricket::MediaContentDescription*, cricket::TransportDescription*, std::__1::vector<webrtc::JsepIceCandidate*, std::__1::allocator<webrtc::JsepIceCandidate*> >*, webrtc::SdpParseError*) in libTwilioVoice.a(webrtcsdp.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::at(unsigned long)", referenced from: (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: rtc::CreateRandomData(unsigned long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) in libTwilioVoice.a(helpers.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: "std::__1::basic_istream<char, std::__1::char_traits<char> >::~basic_istream()", referenced from: (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: std::__1::basic_istringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_istringstream() in libTwilioVoice.a(mediaconstraintsinterface.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: resip::Data::fromFile(resip::Data const&) in libTwilioVoice.a(Data.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: std::__1::basic_ifstream<char, std::__1::char_traits<char> >::~basic_ifstream() in libTwilioVoice.a(Data.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: virtual thunk to std::__1::basic_ifstream<char, std::__1::char_traits<char> >::~basic_ifstream() in libTwilioVoice.a(Data.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: std::__1::basic_ifstream<char, std::__1::char_traits<char> >::~basic_ifstream() in libTwilioVoice.a(Data.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: virtual thunk to std::__1::basic_ifstream<char, std::__1::char_traits<char> >::~basic_ifstream() in libTwilioVoice.a(Data.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: "std::__1::__get_classname(char const*, bool)", referenced from: (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: unsigned int std::__1::regex_traits<char>::__lookup_classname<std::__1::__wrap_iter<char const*> >(std::__1::__wrap_iter<char const*>, std::__1::__wrap_iter<char const*>, bool, char) const in libTwilioVoice.a(voice_sdp_utils.cpp.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: "std::__1::basic_istream<char, std::__1::char_traits<char> >::operator>>(int&)", referenced from: (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: bool (anonymous namespace)::FindConstraint<int>(webrtc::MediaConstraintsInterface const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int*, unsigned long*) in libTwilioVoice.a(mediaconstraintsinterface.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: webrtc::(anonymous namespace)::GetSctpPort(cricket::SessionDescription const*) in libTwilioVoice.a(peerconnection.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: int rtc::FromString<int>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libTwilioVoice.a(videocapturertracksource.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: cricket::Codec::GetParam(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int*) const in libTwilioVoice.a(codec.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: bool rtc::FromString<int>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int*) in libTwilioVoice.a(webrtcsdp.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: webrtc::ParsePort(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int*) in libTwilioVoice.a(iceserverparsing.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: bool rtc::FromString<int>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int*) in libTwilioVoice.a(mediasession.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: ... (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: "std::__1::to_string(unsigned int)", referenced from: (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: twilio::voice::CallImpl::OnIceCandidate(webrtc::IceCandidateInterface const*) in libTwilioVoice.a(call_impl.cpp.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: "std::__1::to_string(long long)", referenced from: (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: twilio::voice::processReportAndPostEvent(twilio::media::StatsReport const&, twilio::media::StatsReport const&, twilio::voice::EventObserver&) in libTwilioVoice.a(call_impl.cpp.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: "std::__1::to_string(double)", referenced from: (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: twilio::voice::processReportAndPostEvent(twilio::media::StatsReport const&, twilio::media::StatsReport const&, twilio::voice::EventObserver&) in libTwilioVoice.a(call_impl.cpp.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: "std::__1::basic_istream<char, std::__1::char_traits<char> >::~basic_istream()", referenced from: (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: construction vtable for std::__1::basic_istream<char, std::__1::char_traits<char> >-in-std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libTwilioVoice.a(header_helper.cpp.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: construction vtable for std::__1::basic_istream<char, std::__1::char_traits<char> >-in-std::__1::basic_istringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libTwilioVoice.a(mediaconstraintsinterface.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: construction vtable for std::__1::basic_istream<char, std::__1::char_traits<char> >-in-std::__1::basic_ifstream<char, std::__1::char_traits<char> > in libTwilioVoice.a(Data.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: construction vtable for std::__1::basic_istream<char, resip::DataStream::char_traits<char> >-in-resip::DataStream in libTwilioVoice.a(DataStream.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: "vtable for std::__1::basic_ios<char, std::__1::char_traits<char> >", referenced from: (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: resip::oDataStream::oDataStream(resip::Data&) in libTwilioVoice.a(DataStream.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: resip::DataStream::DataStream(resip::Data&) in libTwilioVoice.a(DataStream.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: resip::SHA1Stream::SHA1Stream() in libTwilioVoice.a(SHA1Stream.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: resip::MD5Stream::MD5Stream() in libTwilioVoice.a(MD5Stream.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: NOTE: a missing vtable usually means the first non-inline virtual member function has no definition. (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: "std::__1::__next_prime(unsigned long)", referenced from: (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: std::__1::__hash_table<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::__unordered_map_hasher<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, std::__1::__unordered_map_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, std::__1::allocator<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >::rehash(unsigned long) in libTwilioVoice.a(peerconnection.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: std::__1::__hash_table<std::__1::__hash_value_type<resip::DialogSetId, resip::DialogSet*>, std::__1::__unordered_map_hasher<resip::DialogSetId, std::__1::__hash_value_type<resip::DialogSetId, resip::DialogSet*>, std::__1::hash<resip::DialogSetId>, true>, std::__1::__unordered_map_equal<resip::DialogSetId, std::__1::__hash_value_type<resip::DialogSetId, resip::DialogSet*>, std::__1::equal_to<resip::DialogSetId>, true>, std::__1::allocator<std::__1::__hash_value_type<resip::DialogSetId, resip::DialogSet*> > >::rehash(unsigned long) in libTwilioVoice.a(DialogUsageManager.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: std::__1::__hash_table<webrtc::AudioReceiveStream*, std::__1::hash<webrtc::AudioReceiveStream*>, std::__1::equal_to<webrtc::AudioReceiveStream*>, std::__1::allocator<webrtc::AudioReceiveStream*> >::rehash(unsigned long) in libTwilioVoice.a(audio_state.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: std::__1::__hash_table<std::__1::__hash_value_type<int, int>, std::__1::__unordered_map_hasher<int, std::__1::__hash_value_type<int, int>, std::__1::hash<int>, true>, std::__1::__unordered_map_equal<int, std::__1::__hash_value_type<int, int>, std::__1::equal_to<int>, true>, std::__1::allocator<std::__1::__hash_value_type<int, int> > >::rehash(unsigned long) in libTwilioVoice.a(webrtcsdp.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: std::__1::__hash_table<unsigned short, std::__1::hash<unsigned short>, std::__1::equal_to<unsigned short>, std::__1::allocator<unsigned short> >::rehash(unsigned long) in libTwilioVoice.a(video_send_stream.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: std::__1::__hash_table<std::__1::__hash_value_type<unsigned long, resip::Handled*>, std::__1::__unordered_map_hasher<unsigned long, std::__1::__hash_value_type<unsigned long, resip::Handled*>, std::__1::hash<unsigned long>, true>, std::__1::__unordered_map_equal<unsigned long, std::__1::__hash_value_type<unsigned long, resip::Handled*>, std::__1::equal_to<unsigned long>, true>, std::__1::allocator<std::__1::__hash_value_type<unsigned long, resip::Handled*> > >::rehash(unsigned long) in libTwilioVoice.a(HandleManager.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: std::__1::__hash_table<std::__1::__hash_value_type<resip::Mime, resip::ContentsFactoryBase*>, std::__1::__unordered_map_hasher<resip::Mime, std::__1::__hash_value_type<resip::Mime, resip::ContentsFactoryBase*>, std::__1::hash<resip::Mime>, true>, std::__1::__unordered_map_equal<resip::Mime, std::__1::__hash_value_type<resip::Mime, resip::ContentsFactoryBase*>, std::__1::equal_to<resip::Mime>, true>, std::__1::allocator<std::__1::__hash_value_type<resip::Mime, resip::ContentsFactoryBase*> > >::rehash(unsigned long) in libTwilioVoice.a(SipMessage.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: ... (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: "virtual thunk to std::__1::basic_istream<char, std::__1::char_traits<char> >::~basic_istream()", referenced from: (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: construction vtable for std::__1::basic_istream<char, std::__1::char_traits<char> >-in-std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libTwilioVoice.a(header_helper.cpp.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: construction vtable for std::__1::basic_istream<char, std::__1::char_traits<char> >-in-std::__1::basic_istringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libTwilioVoice.a(mediaconstraintsinterface.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: construction vtable for std::__1::basic_istream<char, std::__1::char_traits<char> >-in-std::__1::basic_ifstream<char, std::__1::char_traits<char> > in libTwilioVoice.a(Data.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: construction vtable for std::__1::basic_istream<char, resip::DataStream::char_traits<char> >-in-resip::DataStream in libTwilioVoice.a(DataStream.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::append(unsigned long, char)", referenced from: (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: rtc::HttpParseAttributes(char const*, unsigned long, std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >&) in libTwilioVoice.a(httpcommon.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: "std::__1::basic_iostream<char, std::__1::char_traits<char> >::~basic_iostream()", referenced from: (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: construction vtable for std::__1::basic_iostream<char, std::__1::char_traits<char> >-in-std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libTwilioVoice.a(header_helper.cpp.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: construction vtable for std::__1::basic_iostream<char, resip::DataStream::char_traits<char> >-in-resip::DataStream in libTwilioVoice.a(DataStream.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: "non-virtual thunk to std::__1::basic_iostream<char, std::__1::char_traits<char> >::~basic_iostream()", referenced from: (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: construction vtable for std::__1::basic_iostream<char, std::__1::char_traits<char> >-in-std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in libTwilioVoice.a(header_helper.cpp.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: construction vtable for std::__1::basic_iostream<char, resip::DataStream::char_traits<char> >-in-resip::DataStream in libTwilioVoice.a(DataStream.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::compare(unsigned long, unsigned long, char const*) const", referenced from: (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: webrtc::ParseIceServerUrl(webrtc::PeerConnectionInterface::IceServer const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::set<rtc::SocketAddress, std::__1::less<rtc::SocketAddress>, std::__1::allocator<rtc::SocketAddress> >*, std::__1::vector<cricket::RelayServerConfig, std::__1::allocator<cricket::RelayServerConfig> >*) in libTwilioVoice.a(iceserverparsing.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: "std::__1::codecvt<char, char, __mbstate_t>::id", referenced from: (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: std::__1::basic_filebuf<char, std::__1::char_traits<char> >::imbue(std::__1::locale const&) in libTwilioVoice.a(Data.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/error MT5209: Error: std::__1::basic_filebuf<char, std::__1::char_traits<char> >::basic_filebuf() in libTwilioVoice.a(Data.o) (TwilioHub3.iOS) Native linking
/TwilioVoice/TwilioHub3.iOS/MTOUCH: Error MT5202: Native linking failed. Please review the build log. (MT5202) (TwilioHub3.iOS)
/TwilioVoice/TwilioHub3.iOS/clang: Error: linker command failed with exit code 1 (use -v to see invocation) (TwilioHub3.iOS)

**Comment by dkornev** [comment]
I could reproduce the issue using the nuget package. I personally build the project from the source and don't face this one.

Still investigating, I'll let you know when I find a solution

**Comment by dkornev** [comment]
@NVentimiglia 
Adding **-cxx** as an addition mtouch argument fixed the build for me. But I'm not sure that it won't create any other issues.

I'll try to find out why the issue is not reproducible when building the binding from the source. But let me know if the solution helps you.

**Comment by dkornev** [comment]
@NVentimiglia Could you please let me know if it helps with your issue?

**Comment by NVentimiglia** [comment]
@dkornev  Thanks, will look at this in the morning.

**Comment by NVentimiglia** [comment]
@dkornev looks like it is building now, thanks!
